project:
  type: website
  output-dir: docs

website:
  title: "Cow Website"
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - farms.qmd

format:
  html:
    theme:
      -minty
    css: styles.css
    toc: true



